SimchaFund.Web/Models/ErrorViewModel.cs
namespace SimchaFund.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SimchaFund.Web/Controllers/ContributorsController.cs
using Microsoft.AspNetCore.Mvc;
using SimchaFund.Web.Models;
using System.Diagnostics;

namespace SimchaFund.Web.Controllers
{
    public class ContributorsController : Controller
    {
       

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult History()
        {
            return View();
        }





       

    }
}

SimchaFund.Web/Controllers/SimchasController.cs
using Microsoft.AspNetCore.Mvc;

namespace SimchaFund.Web.Controllers
{
    public class SimchasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SimchaFund.Web/Views/Contributors/History.cshtml
      <main role="main" class="pb-3" style="margin-top: 60px;">
            
<div class="header">
    <h1>History for Matty Friedman</h1>
    <h3>Current Balance: $51,111,111,114.00</h3>
</div>

<div class="row header">
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <tr>
                <th>Action</th>
                <th>Date</th>
                <th>Amount</th>
            </tr>
<tr>
    <td>
        Contribution for the Cohen Wedding simcha
    </td>
    <td style="text-align: center; vertical-align: middle;">
        Thursday, 31 March 2022
    </td>
    <td style="text-align: center; vertical-align: middle;">
        -$5.00
    </td>
</tr>            <tr>
    </table>
    </div>
    </div>
    </main>

 

SimchaFund.Web/Views/Contributors/Index.cshtml
<div class="container">
        <main role="main" class="pb-3" style="margin-top: 60px;">
            <div>
    <h1>Contributors</h1>
</div>
<div class="row">
    <div class="col-md-2">
        <button class="btn btn-danger" id="new-contributor">New Contributor</button>
    </div>
    <div class="col-md-6">
        <input type="text" class="form-control-sm" placeholder="Search" id="search"/>
        <button class="btn btn-danger" id="clear">Clear</button>
    </div>
    <div class="col-md-4">
        <h3>Total: $511,636,297,298,873.32</h3>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <tr>
            <th>Deposit</th>
            <th>Name</th>
            <th>Cell</th>
            <th>Balance</th>
            <th>Always Include</th>
            <th>Actions</th>
        </tr>
            <tr>
                <td>
                    <button class="btn btn-success deposit-button" data-contribid="1003">Deposit</button>
                </td>
                <td>Matty Friedman</td>
                <td>
                    917-513-2011
                </td>
                <td>
                    $51,111,111,114.00
                </td>
                <td style="text-align: center;">
                </td>
                <td>
                    <a href="/contributors/history?contribid=1003" class="btn btn-primary">Show History</a>
                    <button data-first-name="Matty" data-last-name="Friedman"
                            data-cell="917-513-2011" data-id="1003" data-always-include="False" data-date="2022-03-14"
                            class="btn btn-danger edit-contrib">
                        Edit
                    </button>
                </td>
    </table>
</div>
<div class="modal fade new-contrib" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">New Contributor</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="/contributors/new">
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>First Name</label>
                            <input class="form-control" id="contributor_first_name" name="firstName" placeholder="First Name" type="text">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Last Name</label>
                            <input class="form-control" id="contributor_last_name" name="lastName" placeholder="Last Name" type="text">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>Cell Number</label>
                            <input class="form-control" id="contributor_cell_number" name="cellNumber" placeholder="Cell Number" type="text">
                        </div>
                        <div class="form-group col-md-6" id="initialDepositDiv">
                            <label>Initial Deposit</label>
                            <input type="text" class="form-control" name="initialDeposit" placeholder="Initial Deposit">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>Created Date</label>
                            <input class="form-control" id="contributor_created_at" name="date" placeholder="Date" type="date">
                        </div>
                        <div>
                            <div class="form-check mt-3 ml-3">
                                <input type="checkbox" class="form-check-input" id="contributor_always_include" name="alwaysInclude" value="true">
                                <label class="form-check-label" for="contributor_always_include">Always Include</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-primary">Save</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade deposit" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Deposit for <span id="deposit-name"></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="/contributors/deposit">
                <input type="hidden" name="contributorId"/>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Amount</label>
                        <input class="form-control" name="amount" placeholder="Deposit Amount" type="text">
                    </div>
                    <div class="form-group">
                        <label>Date</label>
                        <input type="date" name="date" class="form-control" id="datepicker">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <input class="btn btn-primary" name="commit" type="submit" value="Save">
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


        </main>
    </div>
    @section scripts{
        <script scr="~/js/contributer-index.js"></script>
    }

SimchaFund.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimchaFund.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimchaFund.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimchaFund.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contributors" asp-action="Index">Contributors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Simchas" asp-action="Index">Simchas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SimchaFund.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
     <script src="~/js/contributer-index.js"></script>
  

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SimchaFund.Web/Views/Simchas/Index.cshtml
<div class="header">
    <h1>Simchas</h1>
</div>
<div class="row header">
    <div class="col-md-4">
        <button class="btn btn btn-danger" id="new-simcha">New Simcha</button>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <tr>
            <th>Contributions</th>
            <th>Simcha Name</th>
            <th>Contributor Count</th>
            <th>Total</th>
            <th>Date</th>
        </tr>
            <tr>
                <td>
                    <a class="btn btn-primary" href="/simchas/contributions?simchaid=1012">Contributions</a>
                </td>
                <td>Schwartz Grandson</td>
                <td>
                    8 / 11
                </td>
                <td>$137.00</td>
                <td>04/15/2022</td>
            </tr>
                </table>
                </div>
                